# Generated by Django 3.2.15 on 2022-09-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
